### ISSUE TITLE
Adicionar Authors 

### ISSUE THREAD

**Issue by eilins** [eilins/calculandoaPolonesa#3]
Quem criar o arquivo AUTHORS adiciona seu nome e logo após os outros editam e inserem seus respectivos nomes. Assim que adicionarem seus nomes, comentem aqui.

**Comment by flavioduart** [comment]
Comecei o AUTHORS e adicionei o meu :dancers:

**Comment by caahreginaa** [comment]
Adicionei o meu :dancer:

**Comment by eilins** [comment]
Adicionei o meu e está pronto :walking:
